// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJDAnTPU43qnsw_-s5BDOf2MKngXxMk6M',
    appId: '1:573618732498:web:4bcecfe953e62eefa2dc0b',
    messagingSenderId: '573618732498',
    projectId: 'monogram-2b4e3',
    authDomain: 'monogram-2b4e3.firebaseapp.com',
    storageBucket: 'monogram-2b4e3.firebasestorage.app',
    measurementId: 'G-JDMVTH3H93',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPIQz3jtvvAE7_1Qsk6l7Ico_Vw5RcR8M',
    appId: '1:573618732498:android:2826c1c384a6db24a2dc0b',
    messagingSenderId: '573618732498',
    projectId: 'monogram-2b4e3',
    storageBucket: 'monogram-2b4e3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSeV3IcoYDVkvfU02LwM10dfqRTXsE3Ro',
    appId: '1:573618732498:ios:ef47033468c5f864a2dc0b',
    messagingSenderId: '573618732498',
    projectId: 'monogram-2b4e3',
    storageBucket: 'monogram-2b4e3.firebasestorage.app',
    iosBundleId: 'com.monogram.monogram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSeV3IcoYDVkvfU02LwM10dfqRTXsE3Ro',
    appId: '1:573618732498:ios:ef47033468c5f864a2dc0b',
    messagingSenderId: '573618732498',
    projectId: 'monogram-2b4e3',
    storageBucket: 'monogram-2b4e3.firebasestorage.app',
    iosBundleId: 'com.monogram.monogram',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJDAnTPU43qnsw_-s5BDOf2MKngXxMk6M',
    appId: '1:573618732498:web:32e8f5e5fb659c9ca2dc0b',
    messagingSenderId: '573618732498',
    projectId: 'monogram-2b4e3',
    authDomain: 'monogram-2b4e3.firebaseapp.com',
    storageBucket: 'monogram-2b4e3.firebasestorage.app',
    measurementId: 'G-RET05C9JP1',
  );
}
